# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'envive_helper_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        try:
            print('begin setup ui')
            MainWindow.setObjectName("MainWindow")
            MainWindow.resize(1118, 797)
            self.centralwidget = QtWidgets.QWidget(MainWindow)
            self.centralwidget.setObjectName("centralwidget")
            self.mouse_position_x_label = QtWidgets.QLabel(self.centralwidget)
            self.mouse_position_x_label.setGeometry(QtCore.QRect(160, 650, 91, 21))
            self.mouse_position_x_label.setObjectName("mouse_position_x_label")
            self.mouse_position_y_label = QtWidgets.QLabel(self.centralwidget)
            self.mouse_position_y_label.setGeometry(QtCore.QRect(160, 690, 91, 21))
            self.mouse_position_y_label.setObjectName("mouse_position_y_label")
            self.capture_screen_button = QtWidgets.QPushButton(self.centralwidget)
            self.capture_screen_button.setGeometry(QtCore.QRect(160, 740, 111, 41))
            self.capture_screen_button.setObjectName("capture_screen_button")
            self.mouse_position_label = QtWidgets.QLabel(self.centralwidget)
            self.mouse_position_label.setGeometry(QtCore.QRect(40, 650, 81, 21))
            self.mouse_position_label.setObjectName("mouse_position_label")
            self.mouse_detect_button = QtWidgets.QPushButton(self.centralwidget)
            self.mouse_detect_button.setGeometry(QtCore.QRect(300, 740, 111, 41))
            self.mouse_detect_button.setObjectName("mouse_detect_button")
            self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
            self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1121, 631))
            self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
            self.web_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
            self.web_layout.setContentsMargins(0, 0, 0, 0)
            self.web_layout.setObjectName("web_layout")
            self.web_receive_label = QtWidgets.QLabel(self.centralwidget)
            self.web_receive_label.setGeometry(QtCore.QRect(850, 650, 91, 21))
            self.web_receive_label.setObjectName("web_receive_label")
            self.web_receive_type_label = QtWidgets.QLabel(self.centralwidget)
            self.web_receive_type_label.setGeometry(QtCore.QRect(950, 650, 71, 21))
            self.web_receive_type_label.setObjectName("web_receive_type_label")
            self.web_receive_value_label = QtWidgets.QLabel(self.centralwidget)
            self.web_receive_value_label.setGeometry(QtCore.QRect(950, 680, 71, 21))
            self.web_receive_value_label.setObjectName("web_receive_value_label")
            self.web_sent_label = QtWidgets.QLabel(self.centralwidget)
            self.web_sent_label.setGeometry(QtCore.QRect(450, 660, 91, 21))
            self.web_sent_label.setObjectName("web_sent_label")
            self.to_web_data_type = QtWidgets.QLineEdit(self.centralwidget)
            self.to_web_data_type.setGeometry(QtCore.QRect(560, 660, 113, 20))
            self.to_web_data_type.setObjectName("to_web_data_type")
            self.to_web_data_value = QtWidgets.QLineEdit(self.centralwidget)
            self.to_web_data_value.setGeometry(QtCore.QRect(560, 700, 113, 20))
            self.to_web_data_value.setObjectName("to_web_data_value")
            self.send_data_to_web_button = QtWidgets.QPushButton(self.centralwidget)
            self.send_data_to_web_button.setGeometry(QtCore.QRect(560, 740, 121, 41))
            self.send_data_to_web_button.setObjectName("send_data_to_web_button")
            # MainWindow.setCentralWidget(self.centralwidget)

            self.retranslateUi(MainWindow)
            QtCore.QMetaObject.connectSlotsByName(MainWindow)
            print('end setup ui')
        except Exception as e:
            print("ERROR in UI:", e)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mouse_position_x_label.setText(_translate("MainWindow", "X:"))
        self.mouse_position_y_label.setText(_translate("MainWindow", "Y:"))
        self.capture_screen_button.setText(_translate("MainWindow", "Capture Screen"))
        self.mouse_position_label.setText(_translate("MainWindow", "Mouse Position:"))
        self.mouse_detect_button.setText(_translate("MainWindow", "Mouse Detect"))
        self.web_receive_label.setText(_translate("MainWindow", "Data From Web"))
        self.web_receive_type_label.setText(_translate("MainWindow", "Type:"))
        self.web_receive_value_label.setText(_translate("MainWindow", "Value:"))
        self.web_sent_label.setText(_translate("MainWindow", "Data Send to Web"))
        self.send_data_to_web_button.setText(_translate("MainWindow", "Send Data To Web"))
