# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'envive_helper_python/envive_helper_ui2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1118, 704)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 70, 1121, 631))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.web_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.web_layout.setContentsMargins(0, 0, 0, 0)
        self.web_layout.setObjectName("web_layout")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1121, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.radio_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.radio_layout.setContentsMargins(0, 0, 0, 0)
        self.radio_layout.setObjectName("radio_layout")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
